#!/usr/bin/python3
import actfw_core
from datetime import datetime, timedelta, timezone
from s3_uploader import S3Uploader

JST = timezone(timedelta(hours=+9), "JST")

def main():
    # Actcast application
    app = actfw_core.Application()
    # Load act setting
    settings = app.get_settings(
        {
            "region_name": "",
            "aws_access_key_id": "",
            "aws_secret_access_key": "",
            "bucket_name": "",
        }
    )

    actfw_core.notify([{"message": "S3 upload start"}])
    uploader = S3Uploader(settings)
    try:
        uploader.upload(
            "test.txt",
            settings["bucket_name"],
            datetime.now(JST).isoformat() + ".txt",
        )
        actfw_core.notify([{"message": "S3 upload succeeded"}])
    except Exception as e:
        actfw_core.notify([{"message": "S3 upload failed: " + str(e)}])

    app.run()


if __name__ == "__main__":
    main()
