#!/bin/bash

# For kvssink 
readonly SCRIPT_DIR=$(cd $(dirname $0); pwd)
export GST_PLUGIN_PATH="${SCRIPT_DIR}:${GST_PLUGIN_PATH}"
export LD_LIBRARY_PATH="${SCRIPT_DIR}:${LD_LIBRARY_PATH}"

if [ "X${ACTCAST_SOCKS_SERVER}" != "X" ]
then
  SOCKS_PROXY="socks5h://${ACTCAST_SOCKS_SERVER}"
  export http_proxy="${SOCKS_PROXY}"
  export https_proxy="${SOCKS_PROXY}"
fi

exec python3 main.py
