#!/usr/bin/python3

import os
import subprocess

import actfw_core
from drawer import Drawer
from presenter import Presenter
from rtsp_capture import make_rtsp_capture

(CAPTURE_WIDTH, CAPTURE_HEIGHT) = (800, 600)
(DISPLAY_WIDTH, DISPLAY_HEIGHT) = (800, 600)


def get_rtsp_capture(settings):
    rtsp_url = settings["rtsp_url"]
    caps = {
        "width": CAPTURE_WIDTH,
        "height": CAPTURE_HEIGHT,
        "framerate": settings["fps"],
    }
    # Raspberry Pi のバージョンによってデコーダを切り替える
    # https://github.com/Idein/actfw-gstreamer/tree/master#rtspsrc
    is_video_core_6 = os.path.exists("/dev/dri/card0")
    decoder_type = "v4l2" if is_video_core_6 else "omx"
    capture = make_rtsp_capture(rtsp_url, caps, decoder_type)
    return capture


def main():
    # Actcast application
    app = actfw_core.Application()

    # Load act setting
    settings = app.get_settings(
        {
            "display": True,
            "rtsp_url": "rtsp://ip:port/path",
            "fps": 5,
        }
    )

    # CommandServer (for `Take Photo` command)
    cmd = actfw_core.CommandServer()
    app.register_task(cmd)

    # Capture task
    cap = get_rtsp_capture(settings)
    app.register_task(cap)

    drawer = Drawer()
    app.register_task(drawer)
    pres = Presenter(
        cmd,
        use_display=settings["display"],
        display_size=(DISPLAY_WIDTH, DISPLAY_HEIGHT),
    )
    app.register_task(pres)
    cap.connect(drawer)
    drawer.connect(pres)
    app.run()


if __name__ == "__main__":
    import gi

    gi.require_version("Gst", "1.0")

    from gi.repository import Gst

    Gst.init(None)

    main()
